name: Generate Badge

on:
  schedule:
    - cron: '*/5 * * * *' # каждые 5 минут
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Run badge generator
      run: node scripts/generate-badge.js

    - name: Commit and push badge.svg
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add badge.svg
        git commit -m "Update badge.svg" || echo "No changes"
        git push
